### ISSUE TITLE
Compatibility with LL v14?

### ISSUE THREAD

**Issue by JardaG** [cdfa/AutoSetupLongTapFreeze#10]
Not yet tested, but need to know - will it works?

**Comment by cdfa** [comment]
Not yet. There's a bug in LL that makes it impossible to revert the container eventhandler. I'll comment again when it's fixed.

**Comment by cdfa** [comment]
The bug is fixed and a new version is uploaded. If you have any ideas for triggers for the uninstall everywhere function please tell me, because I had to drop this functionality. (See changelog)

**Comment by JardaG** [comment]
Today I installed LL v14 (r2825) and ASLTF v1.8, and it crash LL when try to run/install script. :(

**Comment by JardaG** [comment]
After crashed install I can freeze/unfreeze apps, but every time it says "At line 291: ReferenceError: "log" is not defined." and buttons "view script", "disable", "ok".

**Comment by cdfa** [comment]
I got this too today and it's partly my fault for leaving debugging code in, but it is also a bug introduced in the stable ll14 released, as I'm pretty sure it worked in the last beta (14b7). I will notify Pierre about the bug and let me know if you want me to upload the version without the debug code so you can use it in the latest beta

**Comment by JardaG** [comment]
Thx for quick reply. Waiting for results. Please do not publish debug code at LL script page.
Hope you can also repair uninstall everywhere. I have 17 folders on main screen...

**Comment by cdfa** [comment]
Uploaded a hotfix for LL14. Tell me if you have any other problems

**Comment by JardaG** [comment]
Thx for fast update! :) Install now works well, (un)freezing too, but uninstall still cause LL crashing, is it fixable?

**Comment by cdfa** [comment]
that's weird, i didn't have any uninstall issues on my device. Could you send me a template or backup of your setup, so i can try to fix it?

**Comment by JardaG** [comment]
Probably fixed, when script updated to v1.8.1 and then uninstall then I got the LL crash, but then every install/uninstall works well. Tested with backup. Do you want send it? How?
Now script works like a charm, great! Thank you a lot! :))

**Comment by cdfa** [comment]
ah okay, then me examing your setup is not needed i think. I will post here again when the bug in LL I had to workaround is fixed.

**Comment by JardaG** [comment]
Ops, another problem, it still showing toast "This item doesn't launch an app!" and never timeout...
I got this toast every time when I leave App Drawer back to LL main screen. Script probably refresh all icons and found some issues...

**Comment by JardaG** [comment]
Ohhh, god, LL crash on all folders when I uninstall a script... :( Going thru this...

**Comment by cdfa** [comment]
oh right, i know where the toast is coming from and will try to fix it in a minute. What do you mean excactly by uninstalling the script? Just deleting it from the script editor? Because somehow that doesn't cause any error with me. If you have any ideas for triggers for the uninstall everywhere action i will reimplement that one as well, which should help i think

**Comment by JardaG** [comment]
Well, try to fix it. And I also found the reason, I forgot an old icon on desktop which now point to wrong target because I manually rename *.app file in system to disable it totally (some phone producer sniffing app).
About uninstall - because autosync now work (before not) I assume, after updating to LL14, the updated script probably need to reinstall in ALL folder manually, so every time when I tried to start "uninstall" in folder I got LL crash, then LL restarts and I run ASLTF to "install" script again. Now it looks stable and autosync works. :)

**Comment by cdfa** [comment]
Aha, okay, do you still get the toast when you resume the app now?
And actually only very few script updates would need a reinstall. If it does, I'll put it in the patch notes and otherwise just try without reinstalling first. If you don't get errors it's fine, else reinstall anyway.

**Comment by JardaG** [comment]
No, I did not got the toast now, I removed the wrong icon.
Ok, good idea to inform user about script reinstalling after update.
Hmm, now some another item ad desktop cause showing neverending toast...

**Comment by JardaG** [comment]
Please show some item identification in toast which object cause failure, I can't identify it now.

**Comment by cdfa** [comment]
Yes i was just gonna suggest that. I'll make the change in a bit

**Comment by cdfa** [comment]
Done. I couldn't really test it, because i don't have such item in my test environment, but it should work.

**Comment by JardaG** [comment]
Not sure it work, it say "null doesn't launch an app!"...

**Comment by cdfa** [comment]
oops, you're right. 1.8.1.2 out now!

**Comment by JardaG** [comment]
YES! :) It is "Work Chat" shortcut created for Evernote.
How to create - launch Evernote, from left menu select "Work Chat", then open user menu "..." on right and select "Add to home screen".
Is this generally identifiable object to ignore it?

**Comment by JardaG** [comment]
But I did not understand why this toast never timeout and is still on screen... Every time I must kill LL manually co clear this.

**Comment by cdfa** [comment]
I don't know that either. I think I will just change it so the toast only pops up when the user is trying to freeze an item and not when the container is trying to sync it's items.

**Comment by JardaG** [comment]
Interesting thing... I disabled autosync and now using "Sync frozen-state" menu item (at LL home screen).
Toast never showed for first try of "Sync frozen-state", (after LL restarted for clear old toast), but then every time. Also I always seen SuperSU toast, so maybe conflict of toasts over itself make timeout issue...?

**Comment by JardaG** [comment]
I'm sure that autosync show toast info, for example when I leave App Drawer, as I wrote before.

**Comment by cdfa** [comment]
I don't think toast collisions could be the problem, because android has a very nicely working system for that. It might be the fact that syncs are not done in the GUI-thread, but i'm not sure. Anyways you shouldn't get any toast notification when syncing anymore in 1.8.1.3

**Comment by JardaG** [comment]
Great! :) Thx a lot! =)
