### ISSUE TITLE
Add menu - Items... - Freeze/Unfreeze all icons

### ISSUE THREAD

**Issue by JardaG** [cdfa/AutoSetupLongTapFreeze#11]
For folders of prepared icons for various situations.
For example:
* for my car navigation is needed to unfreeze 3-4 apps,
* for communication (like mail, messengers, social media) ~7 apps,
* for app data updates (offline maps, public timetable, xposed plugins, ...) more than 15 apps.
Please add it to same menu as "Sync frozen-state".

**Comment by cdfa** [comment]
This is possible and would even be not that hard to do, don't you think it would be better if you could just long tap on a folder icon and then all items in that folder wil be frozen/unfrozen. This would not be applicable to panels though, so if you want that, I can implement both.

**Comment by JardaG** [comment]
Wow, thx, this is good idea to (un)freeze by long tap on folder! :)

**Comment by cdfa** [comment]
it wasn't as easy as it seemed, but the functionality is added in 1.8.3
