### ISSUE TITLE
Icons on desktop did not changed to gray after script installation

### ISSUE THREAD

**Issue by JardaG** [cdfa/AutoSetupLongTapFreeze#6]
First installation of script ends with bug #5 and some icons (~10 of 120) changed to gray, but uninstalling did not revert changes and some icons stayed gray (~5 of 120).
Then I use workaround for #5 and tried to install script again (without error), but right icons never changed to gray. Tried more times.
Maybe some tag issue exists after wrong initialization?
LL v12.9b3 
ASLTF v1.5b1

**Comment by cdfa** [comment]
should also be solved now
