### ISSUE TITLE
Too long desktop refresh when going to LL home

### ISSUE THREAD

**Issue by JardaG** [cdfa/AutoSetupLongTapFreeze#7]
When script installed on my phone it take ~10 seconds to show main desktop with ~120 icons.
Installation on this desktop takes about 20 seconds.
Suggestion 1: try to solve issue #1.
Suggestion 2: add choice to disable auto sync on selected desktops only.
Phone: CPU MT6589T 1.5GHz quad-core, RAM 2 GB, Android v4.2.1
LL v12.9b3
ASLTF v1.5b1

**Comment by cdfa** [comment]
Is this better now that i have implemented multithreading?

**Comment by JardaG** [comment]
Yes, after more than one month of using script v1.7 I'm really satisfied! :)
